# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_title', models.CharField(max_length=64)),
                ('floor', models.IntegerField()),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Audience',
        ),
    ]
