# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20170421_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='audience_title',
            new_name='title',
        ),
    ]
