# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
